FROM ghcr.io/actions/actions-runner:latest

USER root

# AWS CLI 설치
RUN apt-get update && \
    apt-get install -y unzip curl git jq && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 필요한 추가 도구 설치
RUN apt-get update && \
    apt-get install -y curl && \
    curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.7/2025-04-17/bin/linux/arm64/kubectl && \
    chmod +x ./kubectl && \
    mkdir -p /usr/local/bin && \
    cp ./kubectl /usr/local/bin/kubectl && \
    echo 'export PATH=/usr/local/bin:$PATH' >> /etc/profile && \
    rm ./kubectl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# 설치 검증 아래는 주석 가능
RUN echo "🔍 Verifying installed tools..." && \
    aws --version && echo "✅ AWS CLI installed" && \
    which aws && \
    kubectl version --client=true --output=yaml || true && echo "✅ kubectl installed" && \
    which kubectl && \
    git --version && echo "✅ Git installed" && \
    jq --version && echo "✅ jq installed"

USER runner